### ISSUE TITLE
Проверьте ДЗ-1 по Spring

### ISSUE THREAD

**Issue by mcarov** [mcarov/post-processors-test#1]

**Comment by mcarov** [comment]
@coursar проверьте дз

**Comment by coursar** [comment]
1. Вы же должны были сделать свой PropertyPlaceholderConfigurer, который подставляет значения из json
2. Кэшировать-то надо в зависимости от значения аргумента
3. RequestClient должен вычитывать из json (а не по сети) - хотя конкретно это не принципиально

и ключевое - RequestClient не должен болтаться рядом с Main'ом
