### ISSUE TITLE
Кэширование не учитывает аргументы

### ISSUE THREAD

**Issue by coursar** [mcarov/post-processors-test#2]
```java
        {
            var context = new ClassPathXmlApplicationContext("beans.xml");
            var bean = context.getBean("xmlClient", XmlRequestClient.class);
            for (int i = 0; i < 2; i++) {
                System.out.println(bean.getPost(100 + i));
                Thread.sleep(500);
            }
        }
```

Всегда будет один и тот же пост, хотя id - разные

**Comment by mcarov** [comment]
Не очень понимаю, как это сделать...
Попытался из метода вытащить значение аргумента через reflection, не получилось.
Нужно в контексте регистрировать еще один бин и кешировать его вместо RequestClient?

**Comment by mcarov** [comment]
@coursar ,
Не понимаю, как это сделать...
Попытался из метода вытащить значение аргумента через reflection, не получилось.
Нужно в контексте регистрировать еще один бин и кешировать его вместо RequestClient?

**Comment by coursar** [comment]
https://github.com/mcarov/post-processors-test/blob/c76819398449b1674f0613a4610fd76bddcbbd05/src/main/java/ru/itpark/app/Processor.java#L41

Вот здесь у вас есть доступ к аргументам
